### ISSUE TITLE
TimeseriesChart zoom-levels are reset when updating hiddenSeries prop

### ISSUE THREAD

**Issue by hernil** [cognitedata/gearbox.js#555]
When updating the `hiddenSeries` prop of TimeseriesChart the custom zoom-level defined by the user is reset to defaults. This is not the best behaviour from a UX point of view!

**Comment by nalaka** [comment]
In `TimeseriesChart`, x-axis zoom level is set by setting `startTime` and `endTime`- looks like there is no prop exposed to control y-axis zoom level.

The default value for zoom level are

```typescript
startTime: Date.now() - 60 * 60 * 1000,
endTime: Date.now(),
```

When any prop change- such as the `hiddenSeries` prop mentioned by @hernil, the component re-renders, resetting above two props to the defaults.

I think the solution is to keep startTime and endTime in component state.

@mrtraser - does this assessment looks correct?

**Comment by mrtraser** [comment]
Not exactly. Zoom level is not related to `startTime` and `endTime` props, it comes as an internal feature of `griff-react` library.

Btw, guys from OpInt solved this issue in their app, so you could have that solution as a reference

**Comment by mrtraser** [comment]
Blocked by #587

**Comment by nalaka** [comment]
This seems to be a version compatibility issue between gearbox & griff-react.

@hernil -because Gearbox doesn't use the latest **default** version of griff-react- it is possible that you may have done a `yarn add @cognite/griff-react`  instead of `yarn add @cognite/griff-react@~0.4.2`

Or rather unlikely, but you may have interpreted the x-axis expansion/clipping that occurs when you hide/unhide time series using the `hiddenSeries` prop. 

PFB a screen recording of an example app I made to reproduce this - the reported issue is not observed.

![Screen Recording 2020-01-09 at 16 44 45 2020-01-09 16_47_22](https://user-images.githubusercontent.com/437578/72063549-fd8ac200-32ff-11ea-8dbe-803c5c164cb4.gif)

In any case, we've created #587 to investigate the feasibility of moving Gearbox to the latest version of griff-react and keeping it up with every release.

**Comment by hernil** [comment]
It seems you are correct and I'm not able to replicate this in the last version of our code. Will reopen an issue if needed. Thanks! :-)
