### ISSUE TITLE
[mdx-stories]: research ability to display callback actions in better way

### ISSUE THREAD

**Issue by mrtraser** [cognitedata/gearbox.js#568]
Have something better then handlers like onClick => e => console.log(e) as it doesn't even show up in the storybook (developer needs to open dev-console to see the result). previously we used action(...) addon but I am guessing it doesn't work with addon-docs. Please, come up with something here. Maybe just render something ourselves?

**Comment by mrtraser** [comment]
Comunity has already asked about  supporting addons inside `addon-docs`:
https://github.com/storybookjs/storybook/issues/6700
https://github.com/storybookjs/storybook/issues/6639

**Comment by amevck** [comment]
According to my research, callback actions can be displayed in the canvas tab, but not in the docs tab. There is still no way to display callback actions in the docs tab. Referring above @mrtraser mentioned issues from Storybook we can see that they are also trying to find a way to support actions in the docs tab (complication is because docs containing multiple stories while canvas containing only one). So we have two options for now.
- keep existing console.log() until the Storybook gives the feature.
- convert all console.log() to actions and put up with it working in the canvas tab only.

**Comment by mrtraser** [comment]
We will stick to `console.log()` approach just for now.
