### ISSUE TITLE
Research possibility to move to griff-react 0.5.*

### ISSUE THREAD

**Issue by mrtraser** [cognitedata/gearbox.js#587]

**Comment by mrtraser** [comment]
Previously, we faced issues on `griff-react@0.5.0-rc56`:
* Zooming into the chart "cleared" the data. So no timeseries showed anymore. 
* Instead of showing average lines with min and max outline we got point data when endTime was not set

Please, check if issues above appear with the latest version of `griff-react` library

**Comment by nalaka** [comment]
@mrtraser 

> Zooming into the chart "cleared" the data. So no timeseries showed anymore.

Yes, this is still an issue when using with the latest published version of griff-react.

> Instead of showing average lines with min and max outline we got point data when endTime was not set

Min/max outline seems to be there but the x-axis labels seems to be all wrong. 

<img width="320" alt="Screenshot 2020-01-11 at 02 56 58" src="https://user-images.githubusercontent.com/437578/72187919-00300900-341f-11ea-9bf3-2232119e930b.png">

Above screenshot was taken with these props (while connected to `itera-dev` tenanet)

```jsx
<TimeseriesChart
  zoomable={true}
  timeseriesIds={[
    21406044457982,
    165252790415312,
  ]}
  startTime={new Date(2019, 4, 1)}
/>
```

Considering that the version that we are using is over 10 months old, there could be many more places that get broken when we update to latest griff-react. When I find more, will create a list of those issues in a new comment below and update as the research progresses. @polomani / @f1cognite - In any case, we need to bite the bullet and upgrade, right?

@evancharlton & @martincognite  - griff-react's API wise, is it safe for Gearbox to switch to the latest release candidate? I am asking because, 0.4 branch seems abandoned and all the cool stuff seems to be happening on master- which we would like to have very much. Also you are releasing 0.5 RCs- like, every week! So will you guys be dropping the `rc` part from those releases anytime soon?

**Comment by polomani** [comment]
I would suggest to file discovered issues directly on griff-react repo.

**Comment by nalaka** [comment]
## Upgrade

Upgraded `@cognite/griff-react` to latest with:

```shell
yarn remove @cognite/griff-react
yarn add  @cognite/griff-react
```

Resulting dependencies are:

```
├─ @cognite/griff-react@0.5.0-rc.76
├─ d3-queue@3.0.7
├─ d3-request@1.0.5
└─ xmlhttprequest@1.8.0
```

## Run tests 

Ran tests with `yarn test` - 3 fail (out of 301 total)

1. TimeseriesChart › renders correctly when ids are specified
2. TimeseriesChart › renders context chart  
3. TimeseriesChart › renders correctly when series are specified

However, the `zoomable` story renders correctly when IDs are specified. 

<img width="633" alt="Screenshot 2020-01-14 at 11 43 01" src="https://user-images.githubusercontent.com/437578/72318734-15c55d00-36c3-11ea-8674-4ad7cb11b78d.png">

Also the `Custom series` story renders correctly when a series is specified.

<img width="633" alt="Screenshot 2020-01-14 at 11 43 57" src="https://user-images.githubusercontent.com/437578/72318765-2d9ce100-36c3-11ea-93f8-57fe5f59c030.png">

## Inspect stories

Visual inspection of all the stories in `TimeseriesChart` and `TimeseriesChartMeta` components showed them working correctly except for data disappearing after zooming-in.

## Results

So in all three failing test cases, it seems that it is the test that is  broken.
For example,  in expectation statements like `expect(wrapper.find('.line').exists()).toBeTruthy()`,  probably the element selector needs to be updated to match changes in the griff-react LineChart structure.

The main observable issue seems to be that after the initial render (where the data seems to be correctly displayed) when zooming in, all the data disappears.

I am guessing this is due to changes related to griff-react's `DataProvider`  along the direction mentioned in  cognitedata/griff-react@5aec1d8 commit- "Refactor the data flow inside of Scaler" by @evancharlton

## Next steps

Created #589 to track the actual upgrade to griff-react - this will involve fixing the TimeseriesChart component, fixing  all its stories, and fixing all the tests.

On the positive side, as griff-react has greatly improved internally in v5, issues like #469 and #555 probably would resolve theseselves with the upgrade.

**Comment by nalaka** [comment]
Closing this as #615 is ready.
